version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 7o}R~=XA1jmz!-aHQ^pA
